export const blogList = [
  {
    id: 1,
    title: "Javascript ",
    category: "Tech",
    subCategory: ["frontend", "ui/ux", "design"],
    description:
   "JavaScript is a high-level, often just-in-time compiled language that conforms to the ECMAScript standard.[14] It has dynamic typing, prototype-based object-orientation, and first-class functions. It is multi-paradigm, supporting event-driven, functional, and imperative programming styles.",    authorName: "Sushmita",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover: "/assets/images/Javascript.png",
  },
  {
    id: 2,
    title: "Artificial Intelligence",
    category: "Tech",
    subCategory: ["Machine Learning"],
    description:"Still, wondering how future technology will change the world? Take a glimpse of artificial intelligence and realize its benefits in integrating big data analytics and machine learning.The two concepts completely revolutionize the world by enabling massive interconnectivity and technologies that link humans to objects. Expect artificial intelligence to change all the sectors of human life.",    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover: "/assets/images/AI.jpg",
  },
  {
    id: 3,
    title: " Big Data Analytics",
    category: "Tech",
    subCategory: [" business intelligence"],
    description:"The study of large amounts of data is possible thanks to the big data analytics system, it allows you to reveal hidden patterns, connections, and correlations. With the help of such modern technologies, the response with the result will be received almost immediately – which saves time and improves business intelligence.",    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover: "/assets/images/bigdata.webp",
  },
  {
    id: 4,
    title: "KGF2",
    category: "Entertainment",
    subCategory: ["Drama,Action"],
    description:"K.G.F: Chapter 2 is a 2022 Indian Kannada-language period action film written and directed by Prashanth Neel, and produced by Vijay Kiragandur under the banner Hombale Films. ",    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover: "/assets/images/kgf2.jpg",
  },
  {
    id: 5,
    title: "Gathering",
    category: "Community",
    subCategory: ["Gather"],
    description:"A community is a social unit (a group of living things) with commonality such as place, norms, religion, values, customs, or identity. Communities may share a sense of place situated in a given geographical area (e.g. a country, village, town, or neighbourhood) or in virtual space through communication platforms",    authorName: "Rahul",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover: "/assets/images/community.jpg",
  },
  {
    id: 6,
    title: "Singing",
    category: "Entertainment",
    subCategory: ["Singing,Dancing"],
    description:"Entertainment is a form of activity that holds the attention and interest of an audience or gives pleasure and delight. It can be an idea or a task, but is more likely to be one of the activities or events",    authorName: "Kapil",
    authorAvatar: "/assets/images/author.jpg",
    createdAt: "Sept 07, 2022",
    cover:
      "/assets/images/entertainment.jpg",
  },

];
